[fix] ci: Update expected cilium connectivity test namespace (#2926)
* fix: Update expected cilium connectivity test namespace

* ci: leverage --force-deploy to delete old cilium-test resources

diff --git a/.pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml b/.pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
--- a/.pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
+++ b/.pipelines/singletenancy/cilium-overlay-withhubble/cilium-overlay-e2e-step-template.yaml
@@ -112,7 +112,9 @@ steps:
   - script: |
       echo "Run Cilium Connectivity Tests"
       cilium status
-      cilium connectivity test --connect-timeout 4s --request-timeout 30s --test '!pod-to-pod-encryption,!node-to-node-encryption'
+      cilium connectivity test --connect-timeout 4s --request-timeout 30s --test '!pod-to-pod-encryption,!node-to-node-encryption' --force-deploy
+      ns=`kubectl get ns | grep cilium-test | awk '{print $1}'`
+      echo "##vso[task.setvariable variable=ciliumNamespace]$ns"
     retryCountOnTaskFailure: 3
     name: "ciliumConnectivityTests"
     displayName: "Run Cilium Connectivity Tests"
@@ -137,15 +139,16 @@ steps:
       kubectl get pod -owide -A
       # Deleting echo-external-node deployment until cilium version matches TODO. https://github.com/cilium/cilium-cli/issues/67 is addressing the change.
       # Saves 17 minutes
-      kubectl delete deploy -n cilium-test echo-external-node
+
+      kubectl delete deploy -n $(ciliumNamespace) echo-external-node
       if [ "$CILIUM_VERSION_TAG" = "cilium-nightly-pipeline" ]; then
-        echo "Check cilium identities in cilium-test namepsace during nightly run"
+        echo "Check cilium identities in $(ciliumNamespace) namepsace during nightly run"
         echo "expect the identities to be deleted when the namespace is deleted"
         kubectl get ciliumidentity | grep cilium-test
       fi
       make test-validate-state
       echo "delete cilium connectivity test resources and re-validate state"
-      kubectl delete ns cilium-test
+      kubectl delete ns $(ciliumNamespace)
       kubectl get pod -owide -A
       make test-validate-state
     name: "validatePods"
@@ -153,11 +156,10 @@ steps:
 
   - script: |
       if [ "$CILIUM_VERSION_TAG" = "cilium-nightly-pipeline" ]; then
-        kubectl get pod -owide -n cilium-test
+        kubectl get pod -owide -n $(ciliumNamespace)
         echo "wait for pod and cilium identity deletion in cilium-test namespace"
-        ns="cilium-test"
         while true; do
-          pods=$(kubectl get pods -n $ns --no-headers=true 2>/dev/null)
+          pods=$(kubectl get pods -n $(ciliumNamespace) --no-headers=true 2>/dev/null)
           if [[ -z "$pods" ]]; then
             echo "No pods found"
               break
@@ -168,9 +170,10 @@ steps:
         echo "Verify cilium identities are deleted from cilium-test"
         checkIdentity="$(kubectl get ciliumidentity -o json | grep cilium-test | jq -e 'length == 0')"
         if [[ -n $checkIdentity ]]; then
-          echo "##[error]Cilium Identities still present in cilium-test namespace"
+          echo "##[error]Cilium Identities still present in $(ciliumNamespace) namespace"
+          exit 1
         else
-          printf -- "Identities deleted from cilium-test namespace\n"
+          printf -- "Identities deleted from $(ciliumNamespace) namespace\n"
         fi
       else
         echo "skip cilium identities check for PR pipeline"
