ci: Add exit code capture for PR pipeline (#3125)
* ci: Add exit code capture for PR pipeline

* ci: ignore errors from cilium status

diff --git a/.pipelines/templates/cilium-cli.yaml b/.pipelines/templates/cilium-cli.yaml
--- a/.pipelines/templates/cilium-cli.yaml
+++ b/.pipelines/templates/cilium-cli.yaml
@@ -1,5 +1,6 @@
 steps:
   - script: |
+      set -e
       echo "install cilium CLI"
       if [[ ${CILIUM_VERSION_TAG#v} =~ ^1.1[1-3].[0-9]{1,2}|1.1[1-3].[0-9]{1,2}-[0-9]{1,6} ]]; then
         echo "Cilium Agent Version ${BASH_REMATCH[0]}"
@@ -17,6 +18,9 @@ steps:
       sha256sum --check cilium-linux-${CLI_ARCH}.tar.gz.sha256sum
       sudo tar xzvfC cilium-linux-${CLI_ARCH}.tar.gz /usr/local/bin
       rm cilium-linux-${CLI_ARCH}.tar.gz{,.sha256sum}
+
+      # We can ignore failures from cilium status as cilium agent will not be in ready status until CNS is installed.
+      set +e
       cilium status
       cilium version
     name: "installCiliumCLI"
